name: Feature Request
description: Request a new feature
title: "[Feature]: "
labels: [ new ]
assignees:
  - MacroMan
body:
  - type: textarea
    id: new-feature
    attributes:
      label: Description
      description: Please detail what you would like to see in Spaces-API.
    validations:
      required: true
